import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TanstackQueryClientProvider from "../stores/providers/tanstack-query-provider";
import ThemeProvider from "../stores/providers/theme-provider";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "TODO-IT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <TanstackQueryClientProvider>
                    <ThemeProvider
                        attribute={"class"}
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </TanstackQueryClientProvider>
            </body>
        </html>
    );
}
